Task/t119777 scan
nsftx/seven-gravity-gateway pull request #23
Opened 2021-12-28 10:48 UTC by dikaso

This PR includes:
 - new option to provide plugin to slave
 - plugin can hook up on init and on load
 - new barcode scan plugin
 
 
 After this PR is approved I need to:
  - document new plugin

2021-12-28 10:59 UTC, dev387 approved these changes

2022-01-10 07:53 UTC, Lanchi approved these changes

2022-01-10 09:46 UTC, ZvonimirBusic requested changes

2022-01-10 09:46 UTC, ZvonimirBusic commented on test/plugin-barcode-scan.js
> +    });
Tests failing

```
1) Barcode scan should emit Slave.ScanFinished when scan is finished:
     TypeError: Should wrap property of object
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:24:15)
      at Function.spy (node_modules/sinon/lib/sinon/spy.js:45:16)
      at Sandbox.spy (node_modules/sinon/lib/sinon/sandbox.js:275:26)
      at Context.<anonymous> (test/plugin-barcode-scan.js:26:25)
      at processImmediate (internal/timers.js:461:21)

  2) Barcode scan should emit Slave.ScanFinished when scan is finished without prefix:
     TypeError: Should wrap property of object
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:24:15)
      at Function.spy (node_modules/sinon/lib/sinon/spy.js:45:16)
      at Sandbox.spy (node_modules/sinon/lib/sinon/sandbox.js:275:26)
      at Context.<anonymous> (test/plugin-barcode-scan.js:44:25)
      at processImmediate (internal/timers.js:461:21)
```

2022-01-10 09:53 UTC, ZvonimirBusic commented on test/plugin-barcode-scan.js
> +    });
eslint complains about `beforeEach` not being recognized so `"mocha": true` should be included in`.eslintrc` `env` property

2022-01-10 11:41 UTC, dikaso commented on src/slave_gateway.js
> +                plugin.setUpOnce(this);
Storage plugin cannot be passed to `plugins` array. Storage plugin is passed to `worker.plugins` array. See https://github.com/nsftx/seven-gravity-gateway/wiki/3.-Usage#351-plugins.

Although I agree with you that we should align implementations but I find it out of scope for this PR.

2022-01-10 11:44 UTC, aida2709 approved these changes

2022-01-10 12:26 UTC, dikaso commented on src/plugin/barcode-scan.js
> +        previousEventReceived = Date.now();
Almost, first time we use it in this line `difference = currentTime - previousEventReceived;` so it has to be initiated with "some" value.

2022-01-10 12:49 UTC, ZvonimirBusic commented on src/plugin/barcode-scan.js
> +        previousEventReceived = Date.now();
@dikaso Either I misunderstood something or we're not referring to same thing.

Here is code sequence:

1. `currentTime = Date.now();`
2. `previousEventReceived= currentTime;`
3. `previousEventReceived = Date.now();`

Why is no 3. done, it already is Date.now() due to 1 and 2.

Another thing that i realized is that `Date.now()` is called 2 times and will therefore be slightly different. It looks to me that variables to which they are assigned should use same value (`currentTime` and `previousKey.receivedAt`)

2022-01-10 13:40 UTC, ZvonimirBusic commented on src/plugin/barcode-scan.js
> +        previousEventReceived = Date.now();
@dikaso previousEventReceived= currentTime; is still done twice?

2022-01-11 11:04 UTC, ZvonimirBusic requested changes
https://github.com/nsftx/seven-gravity-gateway/pull/23#discussion_r781199234

2022-01-11 11:10 UTC, ZvonimirBusic approved these changes

2022-01-17 14:49 UTC, merged